#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SuruTest")]
public partial class LinqDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 擴充性方法定義
  partial void OnCreated();
  partial void Insertbjuser(bjuser instance);
  partial void Updatebjuser(bjuser instance);
  partial void Deletebjuser(bjuser instance);
  partial void Insertpersonal_sport_menu(personal_sport_menu instance);
  partial void Updatepersonal_sport_menu(personal_sport_menu instance);
  partial void Deletepersonal_sport_menu(personal_sport_menu instance);
  partial void InsertSportType(SportType instance);
  partial void UpdateSportType(SportType instance);
  partial void DeleteSportType(SportType instance);
  partial void Insertsetting(setting instance);
  partial void Updatesetting(setting instance);
  partial void Deletesetting(setting instance);
  partial void Insertuser_health(user_health instance);
  partial void Updateuser_health(user_health instance);
  partial void Deleteuser_health(user_health instance);
  #endregion
	
	public LinqDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SuruTestConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public LinqDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LinqDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<bjuser> bjuser
	{
		get
		{
			return this.GetTable<bjuser>();
		}
	}
	
	public System.Data.Linq.Table<personal_sport_menu> personal_sport_menu
	{
		get
		{
			return this.GetTable<personal_sport_menu>();
		}
	}
	
	public System.Data.Linq.Table<SportType> SportType
	{
		get
		{
			return this.GetTable<SportType>();
		}
	}
	
	public System.Data.Linq.Table<setting> setting
	{
		get
		{
			return this.GetTable<setting>();
		}
	}
	
	public System.Data.Linq.Table<user_health> user_health
	{
		get
		{
			return this.GetTable<user_health>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bjuser")]
public partial class bjuser : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _user_id;
	
	private string _u_photo;
	
	private string _u_name;
	
	private string _u_password;
	
	private string _u_email;
	
	private System.Nullable<System.DateTime> _u_birth;
	
	private System.Nullable<bool> _u_gender;
	
	private EntitySet<personal_sport_menu> _personal_sport_menu;
	
	private EntityRef<setting> _setting;
	
	private EntitySet<user_health> _user_health;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onu_photoChanging(string value);
    partial void Onu_photoChanged();
    partial void Onu_nameChanging(string value);
    partial void Onu_nameChanged();
    partial void Onu_passwordChanging(string value);
    partial void Onu_passwordChanged();
    partial void Onu_emailChanging(string value);
    partial void Onu_emailChanged();
    partial void Onu_birthChanging(System.Nullable<System.DateTime> value);
    partial void Onu_birthChanged();
    partial void Onu_genderChanging(System.Nullable<bool> value);
    partial void Onu_genderChanged();
    #endregion
	
	public bjuser()
	{
		this._personal_sport_menu = new EntitySet<personal_sport_menu>(new Action<personal_sport_menu>(this.attach_personal_sport_menu), new Action<personal_sport_menu>(this.detach_personal_sport_menu));
		this._setting = default(EntityRef<setting>);
		this._user_health = new EntitySet<user_health>(new Action<user_health>(this.attach_user_health), new Action<user_health>(this.detach_user_health));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_photo", DbType="NVarChar(MAX)")]
	public string u_photo
	{
		get
		{
			return this._u_photo;
		}
		set
		{
			if ((this._u_photo != value))
			{
				this.Onu_photoChanging(value);
				this.SendPropertyChanging();
				this._u_photo = value;
				this.SendPropertyChanged("u_photo");
				this.Onu_photoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_name", DbType="NVarChar(50)")]
	public string u_name
	{
		get
		{
			return this._u_name;
		}
		set
		{
			if ((this._u_name != value))
			{
				this.Onu_nameChanging(value);
				this.SendPropertyChanging();
				this._u_name = value;
				this.SendPropertyChanged("u_name");
				this.Onu_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_password", DbType="NVarChar(50)")]
	public string u_password
	{
		get
		{
			return this._u_password;
		}
		set
		{
			if ((this._u_password != value))
			{
				this.Onu_passwordChanging(value);
				this.SendPropertyChanging();
				this._u_password = value;
				this.SendPropertyChanged("u_password");
				this.Onu_passwordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_email", DbType="NVarChar(50)")]
	public string u_email
	{
		get
		{
			return this._u_email;
		}
		set
		{
			if ((this._u_email != value))
			{
				this.Onu_emailChanging(value);
				this.SendPropertyChanging();
				this._u_email = value;
				this.SendPropertyChanged("u_email");
				this.Onu_emailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_birth", DbType="Date")]
	public System.Nullable<System.DateTime> u_birth
	{
		get
		{
			return this._u_birth;
		}
		set
		{
			if ((this._u_birth != value))
			{
				this.Onu_birthChanging(value);
				this.SendPropertyChanging();
				this._u_birth = value;
				this.SendPropertyChanged("u_birth");
				this.Onu_birthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_gender", DbType="Bit")]
	public System.Nullable<bool> u_gender
	{
		get
		{
			return this._u_gender;
		}
		set
		{
			if ((this._u_gender != value))
			{
				this.Onu_genderChanging(value);
				this.SendPropertyChanging();
				this._u_gender = value;
				this.SendPropertyChanged("u_gender");
				this.Onu_genderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bjuser_personal_sport_menu", Storage="_personal_sport_menu", ThisKey="user_id", OtherKey="user_id")]
	public EntitySet<personal_sport_menu> personal_sport_menu
	{
		get
		{
			return this._personal_sport_menu;
		}
		set
		{
			this._personal_sport_menu.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bjuser_setting", Storage="_setting", ThisKey="user_id", OtherKey="user_id", IsUnique=true, IsForeignKey=false)]
	public setting setting
	{
		get
		{
			return this._setting.Entity;
		}
		set
		{
			setting previousValue = this._setting.Entity;
			if (((previousValue != value) 
						|| (this._setting.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._setting.Entity = null;
					previousValue.bjuser = null;
				}
				this._setting.Entity = value;
				if ((value != null))
				{
					value.bjuser = this;
				}
				this.SendPropertyChanged("setting");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bjuser_user_health", Storage="_user_health", ThisKey="user_id", OtherKey="user_id")]
	public EntitySet<user_health> user_health
	{
		get
		{
			return this._user_health;
		}
		set
		{
			this._user_health.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_personal_sport_menu(personal_sport_menu entity)
	{
		this.SendPropertyChanging();
		entity.bjuser = this;
	}
	
	private void detach_personal_sport_menu(personal_sport_menu entity)
	{
		this.SendPropertyChanging();
		entity.bjuser = null;
	}
	
	private void attach_user_health(user_health entity)
	{
		this.SendPropertyChanging();
		entity.bjuser = this;
	}
	
	private void detach_user_health(user_health entity)
	{
		this.SendPropertyChanging();
		entity.bjuser = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.personal_sport_menu")]
public partial class personal_sport_menu : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _p_menu_num;
	
	private System.Nullable<int> _user_id;
	
	private System.Nullable<System.DateTime> _spdate;
	
	private System.Nullable<int> _SportID;
	
	private System.Nullable<double> _distance;
	
	private System.Nullable<int> _reps;
	
	private System.Nullable<int> _sets;
	
	private System.Nullable<System.TimeSpan> _times;
	
	private System.Nullable<bool> _finish;
	
	private EntityRef<bjuser> _bjuser;
	
	private EntityRef<SportType> _SportType;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onp_menu_numChanging(int value);
    partial void Onp_menu_numChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void OnspdateChanging(System.Nullable<System.DateTime> value);
    partial void OnspdateChanged();
    partial void OnSportIDChanging(System.Nullable<int> value);
    partial void OnSportIDChanged();
    partial void OndistanceChanging(System.Nullable<double> value);
    partial void OndistanceChanged();
    partial void OnrepsChanging(System.Nullable<int> value);
    partial void OnrepsChanged();
    partial void OnsetsChanging(System.Nullable<int> value);
    partial void OnsetsChanged();
    partial void OntimesChanging(System.Nullable<System.TimeSpan> value);
    partial void OntimesChanged();
    partial void OnfinishChanging(System.Nullable<bool> value);
    partial void OnfinishChanged();
    #endregion
	
	public personal_sport_menu()
	{
		this._bjuser = default(EntityRef<bjuser>);
		this._SportType = default(EntityRef<SportType>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_menu_num", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int p_menu_num
	{
		get
		{
			return this._p_menu_num;
		}
		set
		{
			if ((this._p_menu_num != value))
			{
				this.Onp_menu_numChanging(value);
				this.SendPropertyChanging();
				this._p_menu_num = value;
				this.SendPropertyChanged("p_menu_num");
				this.Onp_menu_numChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
	public System.Nullable<int> user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				if (this._bjuser.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spdate", DbType="Date")]
	public System.Nullable<System.DateTime> spdate
	{
		get
		{
			return this._spdate;
		}
		set
		{
			if ((this._spdate != value))
			{
				this.OnspdateChanging(value);
				this.SendPropertyChanging();
				this._spdate = value;
				this.SendPropertyChanged("spdate");
				this.OnspdateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SportID", DbType="Int")]
	public System.Nullable<int> SportID
	{
		get
		{
			return this._SportID;
		}
		set
		{
			if ((this._SportID != value))
			{
				if (this._SportType.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnSportIDChanging(value);
				this.SendPropertyChanging();
				this._SportID = value;
				this.SendPropertyChanged("SportID");
				this.OnSportIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distance", DbType="Float")]
	public System.Nullable<double> distance
	{
		get
		{
			return this._distance;
		}
		set
		{
			if ((this._distance != value))
			{
				this.OndistanceChanging(value);
				this.SendPropertyChanging();
				this._distance = value;
				this.SendPropertyChanged("distance");
				this.OndistanceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reps", DbType="Int")]
	public System.Nullable<int> reps
	{
		get
		{
			return this._reps;
		}
		set
		{
			if ((this._reps != value))
			{
				this.OnrepsChanging(value);
				this.SendPropertyChanging();
				this._reps = value;
				this.SendPropertyChanged("reps");
				this.OnrepsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sets", DbType="Int")]
	public System.Nullable<int> sets
	{
		get
		{
			return this._sets;
		}
		set
		{
			if ((this._sets != value))
			{
				this.OnsetsChanging(value);
				this.SendPropertyChanging();
				this._sets = value;
				this.SendPropertyChanged("sets");
				this.OnsetsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_times", DbType="Time")]
	public System.Nullable<System.TimeSpan> times
	{
		get
		{
			return this._times;
		}
		set
		{
			if ((this._times != value))
			{
				this.OntimesChanging(value);
				this.SendPropertyChanging();
				this._times = value;
				this.SendPropertyChanged("times");
				this.OntimesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finish", DbType="Bit")]
	public System.Nullable<bool> finish
	{
		get
		{
			return this._finish;
		}
		set
		{
			if ((this._finish != value))
			{
				this.OnfinishChanging(value);
				this.SendPropertyChanging();
				this._finish = value;
				this.SendPropertyChanged("finish");
				this.OnfinishChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bjuser_personal_sport_menu", Storage="_bjuser", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
	public bjuser bjuser
	{
		get
		{
			return this._bjuser.Entity;
		}
		set
		{
			bjuser previousValue = this._bjuser.Entity;
			if (((previousValue != value) 
						|| (this._bjuser.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._bjuser.Entity = null;
					previousValue.personal_sport_menu.Remove(this);
				}
				this._bjuser.Entity = value;
				if ((value != null))
				{
					value.personal_sport_menu.Add(this);
					this._user_id = value.user_id;
				}
				else
				{
					this._user_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("bjuser");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SportType_personal_sport_menu", Storage="_SportType", ThisKey="SportID", OtherKey="SportID", IsForeignKey=true)]
	public SportType SportType
	{
		get
		{
			return this._SportType.Entity;
		}
		set
		{
			SportType previousValue = this._SportType.Entity;
			if (((previousValue != value) 
						|| (this._SportType.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._SportType.Entity = null;
					previousValue.personal_sport_menu.Remove(this);
				}
				this._SportType.Entity = value;
				if ((value != null))
				{
					value.personal_sport_menu.Add(this);
					this._SportID = value.SportID;
				}
				else
				{
					this._SportID = default(Nullable<int>);
				}
				this.SendPropertyChanged("SportType");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SportType")]
public partial class SportType : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _SportID;
	
	private System.Nullable<int> _TypeID;
	
	private string _SportName;
	
	private EntitySet<personal_sport_menu> _personal_sport_menu;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSportIDChanging(int value);
    partial void OnSportIDChanged();
    partial void OnTypeIDChanging(System.Nullable<int> value);
    partial void OnTypeIDChanged();
    partial void OnSportNameChanging(string value);
    partial void OnSportNameChanged();
    #endregion
	
	public SportType()
	{
		this._personal_sport_menu = new EntitySet<personal_sport_menu>(new Action<personal_sport_menu>(this.attach_personal_sport_menu), new Action<personal_sport_menu>(this.detach_personal_sport_menu));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SportID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int SportID
	{
		get
		{
			return this._SportID;
		}
		set
		{
			if ((this._SportID != value))
			{
				this.OnSportIDChanging(value);
				this.SendPropertyChanging();
				this._SportID = value;
				this.SendPropertyChanged("SportID");
				this.OnSportIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeID", DbType="Int")]
	public System.Nullable<int> TypeID
	{
		get
		{
			return this._TypeID;
		}
		set
		{
			if ((this._TypeID != value))
			{
				this.OnTypeIDChanging(value);
				this.SendPropertyChanging();
				this._TypeID = value;
				this.SendPropertyChanged("TypeID");
				this.OnTypeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SportName", DbType="NVarChar(50)")]
	public string SportName
	{
		get
		{
			return this._SportName;
		}
		set
		{
			if ((this._SportName != value))
			{
				this.OnSportNameChanging(value);
				this.SendPropertyChanging();
				this._SportName = value;
				this.SendPropertyChanged("SportName");
				this.OnSportNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SportType_personal_sport_menu", Storage="_personal_sport_menu", ThisKey="SportID", OtherKey="SportID")]
	public EntitySet<personal_sport_menu> personal_sport_menu
	{
		get
		{
			return this._personal_sport_menu;
		}
		set
		{
			this._personal_sport_menu.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_personal_sport_menu(personal_sport_menu entity)
	{
		this.SendPropertyChanging();
		entity.SportType = this;
	}
	
	private void detach_personal_sport_menu(personal_sport_menu entity)
	{
		this.SendPropertyChanging();
		entity.SportType = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.setting")]
public partial class setting : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _user_id;
	
	private System.Nullable<bool> _drink;
	
	private System.Nullable<bool> _fight;
	
	private System.Nullable<bool> _inspire;
	
	private System.Nullable<decimal> _drink_liter;
	
	private System.Nullable<decimal> _BMR;
	
	private EntityRef<bjuser> _bjuser;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void OndrinkChanging(System.Nullable<bool> value);
    partial void OndrinkChanged();
    partial void OnfightChanging(System.Nullable<bool> value);
    partial void OnfightChanged();
    partial void OninspireChanging(System.Nullable<bool> value);
    partial void OninspireChanged();
    partial void Ondrink_literChanging(System.Nullable<decimal> value);
    partial void Ondrink_literChanged();
    partial void OnBMRChanging(System.Nullable<decimal> value);
    partial void OnBMRChanged();
    #endregion
	
	public setting()
	{
		this._bjuser = default(EntityRef<bjuser>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				if (this._bjuser.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drink", DbType="Bit")]
	public System.Nullable<bool> drink
	{
		get
		{
			return this._drink;
		}
		set
		{
			if ((this._drink != value))
			{
				this.OndrinkChanging(value);
				this.SendPropertyChanging();
				this._drink = value;
				this.SendPropertyChanged("drink");
				this.OndrinkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fight", DbType="Bit")]
	public System.Nullable<bool> fight
	{
		get
		{
			return this._fight;
		}
		set
		{
			if ((this._fight != value))
			{
				this.OnfightChanging(value);
				this.SendPropertyChanging();
				this._fight = value;
				this.SendPropertyChanged("fight");
				this.OnfightChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inspire", DbType="Bit")]
	public System.Nullable<bool> inspire
	{
		get
		{
			return this._inspire;
		}
		set
		{
			if ((this._inspire != value))
			{
				this.OninspireChanging(value);
				this.SendPropertyChanging();
				this._inspire = value;
				this.SendPropertyChanged("inspire");
				this.OninspireChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drink_liter", DbType="Decimal(18,3)")]
	public System.Nullable<decimal> drink_liter
	{
		get
		{
			return this._drink_liter;
		}
		set
		{
			if ((this._drink_liter != value))
			{
				this.Ondrink_literChanging(value);
				this.SendPropertyChanging();
				this._drink_liter = value;
				this.SendPropertyChanged("drink_liter");
				this.Ondrink_literChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMR", DbType="Decimal(18,3)")]
	public System.Nullable<decimal> BMR
	{
		get
		{
			return this._BMR;
		}
		set
		{
			if ((this._BMR != value))
			{
				this.OnBMRChanging(value);
				this.SendPropertyChanging();
				this._BMR = value;
				this.SendPropertyChanged("BMR");
				this.OnBMRChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bjuser_setting", Storage="_bjuser", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
	public bjuser bjuser
	{
		get
		{
			return this._bjuser.Entity;
		}
		set
		{
			bjuser previousValue = this._bjuser.Entity;
			if (((previousValue != value) 
						|| (this._bjuser.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._bjuser.Entity = null;
					previousValue.setting = null;
				}
				this._bjuser.Entity = value;
				if ((value != null))
				{
					value.setting = this;
					this._user_id = value.user_id;
				}
				else
				{
					this._user_id = default(int);
				}
				this.SendPropertyChanged("bjuser");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_health")]
public partial class user_health : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _health_num;
	
	private System.Nullable<int> _user_id;
	
	private System.Nullable<bool> _u_gender;
	
	private System.Nullable<int> _age;
	
	private System.Nullable<int> _height;
	
	private System.Nullable<int> _weight;
	
	private System.Nullable<System.DateTime> _insert_date;
	
	private EntityRef<bjuser> _bjuser;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhealth_numChanging(int value);
    partial void Onhealth_numChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void Onu_genderChanging(System.Nullable<bool> value);
    partial void Onu_genderChanged();
    partial void OnageChanging(System.Nullable<int> value);
    partial void OnageChanged();
    partial void OnheightChanging(System.Nullable<int> value);
    partial void OnheightChanged();
    partial void OnweightChanging(System.Nullable<int> value);
    partial void OnweightChanged();
    partial void Oninsert_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oninsert_dateChanged();
    #endregion
	
	public user_health()
	{
		this._bjuser = default(EntityRef<bjuser>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_health_num", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int health_num
	{
		get
		{
			return this._health_num;
		}
		set
		{
			if ((this._health_num != value))
			{
				this.Onhealth_numChanging(value);
				this.SendPropertyChanging();
				this._health_num = value;
				this.SendPropertyChanged("health_num");
				this.Onhealth_numChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
	public System.Nullable<int> user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				if (this._bjuser.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_gender", DbType="Bit")]
	public System.Nullable<bool> u_gender
	{
		get
		{
			return this._u_gender;
		}
		set
		{
			if ((this._u_gender != value))
			{
				this.Onu_genderChanging(value);
				this.SendPropertyChanging();
				this._u_gender = value;
				this.SendPropertyChanged("u_gender");
				this.Onu_genderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
	public System.Nullable<int> age
	{
		get
		{
			return this._age;
		}
		set
		{
			if ((this._age != value))
			{
				this.OnageChanging(value);
				this.SendPropertyChanging();
				this._age = value;
				this.SendPropertyChanged("age");
				this.OnageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_height", DbType="Int")]
	public System.Nullable<int> height
	{
		get
		{
			return this._height;
		}
		set
		{
			if ((this._height != value))
			{
				this.OnheightChanging(value);
				this.SendPropertyChanging();
				this._height = value;
				this.SendPropertyChanged("height");
				this.OnheightChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weight", DbType="Int")]
	public System.Nullable<int> weight
	{
		get
		{
			return this._weight;
		}
		set
		{
			if ((this._weight != value))
			{
				this.OnweightChanging(value);
				this.SendPropertyChanging();
				this._weight = value;
				this.SendPropertyChanged("weight");
				this.OnweightChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_date", DbType="Date")]
	public System.Nullable<System.DateTime> insert_date
	{
		get
		{
			return this._insert_date;
		}
		set
		{
			if ((this._insert_date != value))
			{
				this.Oninsert_dateChanging(value);
				this.SendPropertyChanging();
				this._insert_date = value;
				this.SendPropertyChanged("insert_date");
				this.Oninsert_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bjuser_user_health", Storage="_bjuser", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
	public bjuser bjuser
	{
		get
		{
			return this._bjuser.Entity;
		}
		set
		{
			bjuser previousValue = this._bjuser.Entity;
			if (((previousValue != value) 
						|| (this._bjuser.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._bjuser.Entity = null;
					previousValue.user_health.Remove(this);
				}
				this._bjuser.Entity = value;
				if ((value != null))
				{
					value.user_health.Add(this);
					this._user_id = value.user_id;
				}
				else
				{
					this._user_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("bjuser");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
