#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BJWORK95")]
public partial class LinqDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 擴充性方法定義
  partial void OnCreated();
  partial void Insertpb(pb instance);
  partial void Updatepb(pb instance);
  partial void Deletepb(pb instance);
  partial void Insertusers(users instance);
  partial void Updateusers(users instance);
  partial void Deleteusers(users instance);
  partial void Insertuser_health(user_health instance);
  partial void Updateuser_health(user_health instance);
  partial void Deleteuser_health(user_health instance);
  partial void Insertsport_type(sport_type instance);
  partial void Updatesport_type(sport_type instance);
  partial void Deletesport_type(sport_type instance);
  #endregion
	
	public LinqDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BJWORK95ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public LinqDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LinqDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<pb> pb
	{
		get
		{
			return this.GetTable<pb>();
		}
	}
	
	public System.Data.Linq.Table<users> users
	{
		get
		{
			return this.GetTable<users>();
		}
	}
	
	public System.Data.Linq.Table<user_health> user_health
	{
		get
		{
			return this.GetTable<user_health>();
		}
	}
	
	public System.Data.Linq.Table<sport_type> sport_type
	{
		get
		{
			return this.GetTable<sport_type>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pb")]
public partial class pb : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pbnum;
	
	private int _user_id;
	
	private int _sport_id;
	
	private System.Nullable<double> _distance;
	
	private System.Nullable<int> _sets;
	
	private System.Nullable<int> _reps;
	
	private string _times;
	
	private System.Nullable<double> _calories;
	
	private System.DateTime _dates;
	
	private System.Nullable<int> _pound;
	
	private EntityRef<users> _users;
	
	private EntityRef<sport_type> _sport_type;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpbnumChanging(int value);
    partial void OnpbnumChanged();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onsport_idChanging(int value);
    partial void Onsport_idChanged();
    partial void OndistanceChanging(System.Nullable<double> value);
    partial void OndistanceChanged();
    partial void OnsetsChanging(System.Nullable<int> value);
    partial void OnsetsChanged();
    partial void OnrepsChanging(System.Nullable<int> value);
    partial void OnrepsChanged();
    partial void OntimesChanging(string value);
    partial void OntimesChanged();
    partial void OncaloriesChanging(System.Nullable<double> value);
    partial void OncaloriesChanged();
    partial void OndatesChanging(System.DateTime value);
    partial void OndatesChanged();
    partial void OnpoundChanging(System.Nullable<int> value);
    partial void OnpoundChanged();
    #endregion
	
	public pb()
	{
		this._users = default(EntityRef<users>);
		this._sport_type = default(EntityRef<sport_type>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pbnum", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pbnum
	{
		get
		{
			return this._pbnum;
		}
		set
		{
			if ((this._pbnum != value))
			{
				this.OnpbnumChanging(value);
				this.SendPropertyChanging();
				this._pbnum = value;
				this.SendPropertyChanged("pbnum");
				this.OnpbnumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL")]
	public int user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				if (this._users.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sport_id", DbType="Int NOT NULL")]
	public int sport_id
	{
		get
		{
			return this._sport_id;
		}
		set
		{
			if ((this._sport_id != value))
			{
				if (this._sport_type.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onsport_idChanging(value);
				this.SendPropertyChanging();
				this._sport_id = value;
				this.SendPropertyChanged("sport_id");
				this.Onsport_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distance", DbType="Float")]
	public System.Nullable<double> distance
	{
		get
		{
			return this._distance;
		}
		set
		{
			if ((this._distance != value))
			{
				this.OndistanceChanging(value);
				this.SendPropertyChanging();
				this._distance = value;
				this.SendPropertyChanged("distance");
				this.OndistanceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sets", DbType="Int")]
	public System.Nullable<int> sets
	{
		get
		{
			return this._sets;
		}
		set
		{
			if ((this._sets != value))
			{
				this.OnsetsChanging(value);
				this.SendPropertyChanging();
				this._sets = value;
				this.SendPropertyChanged("sets");
				this.OnsetsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reps", DbType="Int")]
	public System.Nullable<int> reps
	{
		get
		{
			return this._reps;
		}
		set
		{
			if ((this._reps != value))
			{
				this.OnrepsChanging(value);
				this.SendPropertyChanging();
				this._reps = value;
				this.SendPropertyChanged("reps");
				this.OnrepsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_times", DbType="NVarChar(50)")]
	public string times
	{
		get
		{
			return this._times;
		}
		set
		{
			if ((this._times != value))
			{
				this.OntimesChanging(value);
				this.SendPropertyChanging();
				this._times = value;
				this.SendPropertyChanged("times");
				this.OntimesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calories", DbType="Float")]
	public System.Nullable<double> calories
	{
		get
		{
			return this._calories;
		}
		set
		{
			if ((this._calories != value))
			{
				this.OncaloriesChanging(value);
				this.SendPropertyChanging();
				this._calories = value;
				this.SendPropertyChanged("calories");
				this.OncaloriesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dates", DbType="DateTime NOT NULL")]
	public System.DateTime dates
	{
		get
		{
			return this._dates;
		}
		set
		{
			if ((this._dates != value))
			{
				this.OndatesChanging(value);
				this.SendPropertyChanging();
				this._dates = value;
				this.SendPropertyChanged("dates");
				this.OndatesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pound", DbType="Int")]
	public System.Nullable<int> pound
	{
		get
		{
			return this._pound;
		}
		set
		{
			if ((this._pound != value))
			{
				this.OnpoundChanging(value);
				this.SendPropertyChanging();
				this._pound = value;
				this.SendPropertyChanged("pound");
				this.OnpoundChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_pb", Storage="_users", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
	public users users
	{
		get
		{
			return this._users.Entity;
		}
		set
		{
			users previousValue = this._users.Entity;
			if (((previousValue != value) 
						|| (this._users.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._users.Entity = null;
					previousValue.pb.Remove(this);
				}
				this._users.Entity = value;
				if ((value != null))
				{
					value.pb.Add(this);
					this._user_id = value.user_id;
				}
				else
				{
					this._user_id = default(int);
				}
				this.SendPropertyChanged("users");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sport_type_pb", Storage="_sport_type", ThisKey="sport_id", OtherKey="sport_id", IsForeignKey=true)]
	public sport_type sport_type
	{
		get
		{
			return this._sport_type.Entity;
		}
		set
		{
			sport_type previousValue = this._sport_type.Entity;
			if (((previousValue != value) 
						|| (this._sport_type.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._sport_type.Entity = null;
					previousValue.pb.Remove(this);
				}
				this._sport_type.Entity = value;
				if ((value != null))
				{
					value.pb.Add(this);
					this._sport_id = value.sport_id;
				}
				else
				{
					this._sport_id = default(int);
				}
				this.SendPropertyChanged("sport_type");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
public partial class users : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _user_id;
	
	private string _u_name;
	
	private string _u_photo;
	
	private string _u_password;
	
	private string _u_email;
	
	private System.Nullable<System.DateTime> _u_birth;
	
	private bool _u_sex;
	
	private System.Nullable<int> _u_atk;
	
	private System.Nullable<int> _u_win;
	
	private EntitySet<pb> _pb;
	
	private EntitySet<user_health> _user_health;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onu_nameChanging(string value);
    partial void Onu_nameChanged();
    partial void Onu_photoChanging(string value);
    partial void Onu_photoChanged();
    partial void Onu_passwordChanging(string value);
    partial void Onu_passwordChanged();
    partial void Onu_emailChanging(string value);
    partial void Onu_emailChanged();
    partial void Onu_birthChanging(System.Nullable<System.DateTime> value);
    partial void Onu_birthChanged();
    partial void Onu_sexChanging(bool value);
    partial void Onu_sexChanged();
    partial void Onu_atkChanging(System.Nullable<int> value);
    partial void Onu_atkChanged();
    partial void Onu_winChanging(System.Nullable<int> value);
    partial void Onu_winChanged();
    #endregion
	
	public users()
	{
		this._pb = new EntitySet<pb>(new Action<pb>(this.attach_pb), new Action<pb>(this.detach_pb));
		this._user_health = new EntitySet<user_health>(new Action<user_health>(this.attach_user_health), new Action<user_health>(this.detach_user_health));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string u_name
	{
		get
		{
			return this._u_name;
		}
		set
		{
			if ((this._u_name != value))
			{
				this.Onu_nameChanging(value);
				this.SendPropertyChanging();
				this._u_name = value;
				this.SendPropertyChanged("u_name");
				this.Onu_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_photo", DbType="NVarChar(MAX)")]
	public string u_photo
	{
		get
		{
			return this._u_photo;
		}
		set
		{
			if ((this._u_photo != value))
			{
				this.Onu_photoChanging(value);
				this.SendPropertyChanging();
				this._u_photo = value;
				this.SendPropertyChanged("u_photo");
				this.Onu_photoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string u_password
	{
		get
		{
			return this._u_password;
		}
		set
		{
			if ((this._u_password != value))
			{
				this.Onu_passwordChanging(value);
				this.SendPropertyChanging();
				this._u_password = value;
				this.SendPropertyChanged("u_password");
				this.Onu_passwordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string u_email
	{
		get
		{
			return this._u_email;
		}
		set
		{
			if ((this._u_email != value))
			{
				this.Onu_emailChanging(value);
				this.SendPropertyChanging();
				this._u_email = value;
				this.SendPropertyChanged("u_email");
				this.Onu_emailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_birth", DbType="Date")]
	public System.Nullable<System.DateTime> u_birth
	{
		get
		{
			return this._u_birth;
		}
		set
		{
			if ((this._u_birth != value))
			{
				this.Onu_birthChanging(value);
				this.SendPropertyChanging();
				this._u_birth = value;
				this.SendPropertyChanged("u_birth");
				this.Onu_birthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_sex", DbType="Bit NOT NULL")]
	public bool u_sex
	{
		get
		{
			return this._u_sex;
		}
		set
		{
			if ((this._u_sex != value))
			{
				this.Onu_sexChanging(value);
				this.SendPropertyChanging();
				this._u_sex = value;
				this.SendPropertyChanged("u_sex");
				this.Onu_sexChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_atk", DbType="Int")]
	public System.Nullable<int> u_atk
	{
		get
		{
			return this._u_atk;
		}
		set
		{
			if ((this._u_atk != value))
			{
				this.Onu_atkChanging(value);
				this.SendPropertyChanging();
				this._u_atk = value;
				this.SendPropertyChanged("u_atk");
				this.Onu_atkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_win", DbType="Int")]
	public System.Nullable<int> u_win
	{
		get
		{
			return this._u_win;
		}
		set
		{
			if ((this._u_win != value))
			{
				this.Onu_winChanging(value);
				this.SendPropertyChanging();
				this._u_win = value;
				this.SendPropertyChanged("u_win");
				this.Onu_winChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_pb", Storage="_pb", ThisKey="user_id", OtherKey="user_id")]
	public EntitySet<pb> pb
	{
		get
		{
			return this._pb;
		}
		set
		{
			this._pb.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_user_health", Storage="_user_health", ThisKey="user_id", OtherKey="user_id")]
	public EntitySet<user_health> user_health
	{
		get
		{
			return this._user_health;
		}
		set
		{
			this._user_health.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_pb(pb entity)
	{
		this.SendPropertyChanging();
		entity.users = this;
	}
	
	private void detach_pb(pb entity)
	{
		this.SendPropertyChanging();
		entity.users = null;
	}
	
	private void attach_user_health(user_health entity)
	{
		this.SendPropertyChanging();
		entity.users = this;
	}
	
	private void detach_user_health(user_health entity)
	{
		this.SendPropertyChanging();
		entity.users = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_health")]
public partial class user_health : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _user_health_num;
	
	private int _user_id;
	
	private double _height;
	
	private System.Nullable<decimal> _weight;
	
	private System.Nullable<System.DateTime> _dates;
	
	private System.Nullable<decimal> _BMI;
	
	private System.Nullable<decimal> _BMR;
	
	private System.Nullable<decimal> _drink_liter;
	
	private System.Nullable<int> _age;
	
	private EntityRef<users> _users;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_health_numChanging(int value);
    partial void Onuser_health_numChanged();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void OnheightChanging(double value);
    partial void OnheightChanged();
    partial void OnweightChanging(System.Nullable<decimal> value);
    partial void OnweightChanged();
    partial void OndatesChanging(System.Nullable<System.DateTime> value);
    partial void OndatesChanged();
    partial void OnBMIChanging(System.Nullable<decimal> value);
    partial void OnBMIChanged();
    partial void OnBMRChanging(System.Nullable<decimal> value);
    partial void OnBMRChanged();
    partial void Ondrink_literChanging(System.Nullable<decimal> value);
    partial void Ondrink_literChanged();
    partial void OnageChanging(System.Nullable<int> value);
    partial void OnageChanged();
    #endregion
	
	public user_health()
	{
		this._users = default(EntityRef<users>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_health_num", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int user_health_num
	{
		get
		{
			return this._user_health_num;
		}
		set
		{
			if ((this._user_health_num != value))
			{
				this.Onuser_health_numChanging(value);
				this.SendPropertyChanging();
				this._user_health_num = value;
				this.SendPropertyChanged("user_health_num");
				this.Onuser_health_numChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL")]
	public int user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				if (this._users.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_height", DbType="Float NOT NULL")]
	public double height
	{
		get
		{
			return this._height;
		}
		set
		{
			if ((this._height != value))
			{
				this.OnheightChanging(value);
				this.SendPropertyChanging();
				this._height = value;
				this.SendPropertyChanged("height");
				this.OnheightChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weight", DbType="Decimal(18,1)")]
	public System.Nullable<decimal> weight
	{
		get
		{
			return this._weight;
		}
		set
		{
			if ((this._weight != value))
			{
				this.OnweightChanging(value);
				this.SendPropertyChanging();
				this._weight = value;
				this.SendPropertyChanged("weight");
				this.OnweightChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dates", DbType="DateTime")]
	public System.Nullable<System.DateTime> dates
	{
		get
		{
			return this._dates;
		}
		set
		{
			if ((this._dates != value))
			{
				this.OndatesChanging(value);
				this.SendPropertyChanging();
				this._dates = value;
				this.SendPropertyChanged("dates");
				this.OndatesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI", DbType="Decimal(18,3)")]
	public System.Nullable<decimal> BMI
	{
		get
		{
			return this._BMI;
		}
		set
		{
			if ((this._BMI != value))
			{
				this.OnBMIChanging(value);
				this.SendPropertyChanging();
				this._BMI = value;
				this.SendPropertyChanged("BMI");
				this.OnBMIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMR", DbType="Decimal(18,3)")]
	public System.Nullable<decimal> BMR
	{
		get
		{
			return this._BMR;
		}
		set
		{
			if ((this._BMR != value))
			{
				this.OnBMRChanging(value);
				this.SendPropertyChanging();
				this._BMR = value;
				this.SendPropertyChanged("BMR");
				this.OnBMRChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drink_liter", DbType="Decimal(18,3)")]
	public System.Nullable<decimal> drink_liter
	{
		get
		{
			return this._drink_liter;
		}
		set
		{
			if ((this._drink_liter != value))
			{
				this.Ondrink_literChanging(value);
				this.SendPropertyChanging();
				this._drink_liter = value;
				this.SendPropertyChanged("drink_liter");
				this.Ondrink_literChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
	public System.Nullable<int> age
	{
		get
		{
			return this._age;
		}
		set
		{
			if ((this._age != value))
			{
				this.OnageChanging(value);
				this.SendPropertyChanging();
				this._age = value;
				this.SendPropertyChanged("age");
				this.OnageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_user_health", Storage="_users", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
	public users users
	{
		get
		{
			return this._users.Entity;
		}
		set
		{
			users previousValue = this._users.Entity;
			if (((previousValue != value) 
						|| (this._users.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._users.Entity = null;
					previousValue.user_health.Remove(this);
				}
				this._users.Entity = value;
				if ((value != null))
				{
					value.user_health.Add(this);
					this._user_id = value.user_id;
				}
				else
				{
					this._user_id = default(int);
				}
				this.SendPropertyChanged("users");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sport_type")]
public partial class sport_type : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _type_id;
	
	private int _sport_id;
	
	private string _sport_name;
	
	private string _sport_photo;
	
	private EntitySet<pb> _pb;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontype_idChanging(int value);
    partial void Ontype_idChanged();
    partial void Onsport_idChanging(int value);
    partial void Onsport_idChanged();
    partial void Onsport_nameChanging(string value);
    partial void Onsport_nameChanged();
    partial void Onsport_photoChanging(string value);
    partial void Onsport_photoChanged();
    #endregion
	
	public sport_type()
	{
		this._pb = new EntitySet<pb>(new Action<pb>(this.attach_pb), new Action<pb>(this.detach_pb));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_id", DbType="Int NOT NULL")]
	public int type_id
	{
		get
		{
			return this._type_id;
		}
		set
		{
			if ((this._type_id != value))
			{
				this.Ontype_idChanging(value);
				this.SendPropertyChanging();
				this._type_id = value;
				this.SendPropertyChanged("type_id");
				this.Ontype_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sport_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int sport_id
	{
		get
		{
			return this._sport_id;
		}
		set
		{
			if ((this._sport_id != value))
			{
				this.Onsport_idChanging(value);
				this.SendPropertyChanging();
				this._sport_id = value;
				this.SendPropertyChanged("sport_id");
				this.Onsport_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sport_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string sport_name
	{
		get
		{
			return this._sport_name;
		}
		set
		{
			if ((this._sport_name != value))
			{
				this.Onsport_nameChanging(value);
				this.SendPropertyChanging();
				this._sport_name = value;
				this.SendPropertyChanged("sport_name");
				this.Onsport_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sport_photo", DbType="NVarChar(50)")]
	public string sport_photo
	{
		get
		{
			return this._sport_photo;
		}
		set
		{
			if ((this._sport_photo != value))
			{
				this.Onsport_photoChanging(value);
				this.SendPropertyChanging();
				this._sport_photo = value;
				this.SendPropertyChanged("sport_photo");
				this.Onsport_photoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sport_type_pb", Storage="_pb", ThisKey="sport_id", OtherKey="sport_id")]
	public EntitySet<pb> pb
	{
		get
		{
			return this._pb;
		}
		set
		{
			this._pb.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_pb(pb entity)
	{
		this.SendPropertyChanging();
		entity.sport_type = this;
	}
	
	private void detach_pb(pb entity)
	{
		this.SendPropertyChanging();
		entity.sport_type = null;
	}
}
#pragma warning restore 1591
